resources:
- name: repo1
  type: git
  source:
   uri: https://github.com/yprashanth67/lostcause.git
  #  branch: master
  #  username: yprashanth67
  #  password: Infor#8019805055
   
- name: put-repo
  type: git
  source:
    uri: git@github.com:yprashanth67/Test1.git
    branch: master
    private_key: gitpk1.pem



# - name: repo1
#   type: git
#   source:
#    uri: https://github.com/yprashanth67/lostcause.git



jobs:
- name: edit-git
  plan:
  - get: repo1
    trigger: true
  - task: edit-git
    config:
      inputs: 
      - name: repo1
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gitea/gitea
      params:
        EMAIL: yprashanth67@yahoo.com
        GIT_AUTHOR_NAME: Person Doe
      run:
        path: sh
        args: 
        - -cx
        - |
          cd repo1
          date +%Y-%m-%d > todays-date
          date | awk '{print $4}' >> README.md
          git add .
          git config --global user.email $EMAIL
          git config --global user.name $GIT_AUTHOR_NAME
          git commit -m "Update todays date"
      outputs:
      - name: repo1
  - put: put-repo
    params:
      repository: repo1

