resources:
- name: repo
  type: git
  source:
    uri: https://github.com/concourse/examples.git

jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true  
  - task: hello-world-task
    config:
      inputs:
      - name: repo
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      outputs:
      - name: the-artifact
      run:
        path: sh
        args: |
        cat repo/README.md > the-artifact/message
        echo 'appended by hello-world-job' >> the-artifact/message
    config:
      inputs: 
      - name: the-artifact
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: cat
        args: ['the-artifact/message']