jobs:
- name: hello-world-job
  plan: 
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      outputs:
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          echo "hello from another step!" > the-artifact/message
  - task: read-first-task
    config:
      inputs: 
      - name: the-artifact
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: cat
        args: ['the-artifact/message']