private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdz
  c2gtcnNhAAAAAwEAAQAAAYEAzc8zo3aPUMNHeUesELkoYu+O+HfbWoGHfCE58RMe
  8GUHhRvEGaYekgX7vvNhhlLwyFAVbQPioHNfVvCekthdZRPtd22XGXAdCTLSpXbg
  w8Zc9nOZ/2y9QyI7bgtrVYCH/8hVVwAP9aC2LYCMBP9wC4rEMG2ut6FTIvja8jSx
  +xnBNmirGI7AoT1CqllU+m/HqdUS3vTafL/w7q8XuNu5DHpqDFoohKdoOcaQEN6t
  adxPhLGjYXC+HvdYmzxm8vFc06uiSP6I4qacFf/hm2KRz+sG38HJbdWoboeejAQI
  H4m7J9oDvZRr7o6gwXh5a0pgEFtkFj5yjfzpiuiPliea1LXpmXNS82JHTAJ0FqKN
  QBcJsvc8Pm9Tx/zzF7p1KlzrvKoQY26ueZ4zoKdpQaFsPlDSY/zSRTdbWu/ovgix
  9VifKUZeBAzuCbhyQf3qwDOE0p+PkvKfIh/SYqI2HGqxBiShemlMy+y0WaQhdXXw
  /ehx3UPXglAB1jrhbZK81IKdAAAFkPkHdpn5B3aZAAAAB3NzaC1yc2EAAAGBAM3P
  M6N2j1DDR3lHrBC5KGLvjvh321qBh3whOfETHvBlB4UbxBmmHpIF+77zYYZS8MhQ
  FW0D4qBzX1bwnpLYXWUT7XdtlxlwHQky0qV24MPGXPZzmf9svUMiO24La1WAh//I
  VVcAD/Wgti2AjAT/cAuKxDBtrrehUyL42vI0sfsZwTZoqxiOwKE9QqpZVPpvx6nV
  Et702ny/8O6vF7jbuQx6agxaKISnaDnGkBDerWncT4Sxo2Fwvh73WJs8ZvLxXNOr
  okj+iOKmnBX/4Ztikc/rBt/ByW3VqG6HnowECB+JuyfaA72Ua+6OoMF4eWtKYBBb
  ZBY+co386Yroj5YnmtS16ZlzUvNiR0wCdBaijUAXCbL3PD5vU8f88xe6dSpc67yq
  EGNurnmeM6CnaUGhbD5Q0mP80kU3W1rv6L4IsfVYnylGXgQM7gm4ckH96sAzhNKf
  j5LynyIf0mKiNhxqsQYkoXppTMvstFmkIXV18P3ocd1D14JQAdY64W2SvNSCnQAA
  AAMBAAEAAAGALKcW8hFIGOK1gCe/ukUh8Q0+vMPscJ+H0LO4yYg3fzq8PfH/Qv1a
  xp3Lt+tALo+SNDPD4kokgmFlvwwnq36MDOEc9XtufBNqCVPghgvbyj4gb0w3jkZ+
  bbFgqYiKuhtP5nwFoAGgdM9wl0C7oF33ZlmuJT+215qF2iGaB1DNiMhWtkJRVNus
  CY+sBh+po0hbToqvNHZ1bPmMAY01nWL2rDFnDtUE03sqztY47aASidRF4GlWJE78
  wOUzcULSp0UcVioRPZlJUi4RMHFO28Ka5mYfNSrrwjU5hPkfPlsCifg/Zq0Wtx4v
  ox1hs/w8JHAnWXsqts2Zpbl091rSmVhdL1s5Jc3dLBpDgW63NeZ89rRPN2WaLR1f
  QVKZPqzaPeIqfVVaADujJVFTVepC9zp7sqdwdU1Lpo9NL+h87V+cmTMHY3y0C6SH
  EalbHP/ekXgANJfG9lPnpBwMuDaEZk5anOxI0Pi1yZLBQ8wLYcT02xQ0W8Ioeccq
  +ADwnOtKmPdVAAAAwHHqLoVWT/SLdPWU8/5KbysopGTdcQjmxvCSzVMBQ8eNK0bI
  oOL90vl8hBbwQwZWdV9dNX1oXZvJQE55/eu1/6YGWX92HH8bQdfO6Uj0x1M/r0lr
  3/ynUKvzFXw+ipbc7mpzH3C56Tfm4q7TwiTyUizhlb3WUqrcoyyq/6C7Wyfzu2kB
  ByvQDpv10APut5ZvR2Xvta/ngY6P9T8KxcUzGHBwPUECEdztjnB5epW6xgapsJ/m
  w02rgXiY/eoHON4JsQAAAMEA5hkmLFXwqPQin/q4O6OzcGnBGf0Lsyje2JeNgKh2
  +IMLTapWcXF9Lj/FQUz9tUqQ7XxxMuMaJYCPaTE7S9gTTKvZwzQm0VXKrmkuvOUS
  hTznMVQhi/2zD4eflcp8ejKad31SYmO3DWzQpyB+0k2EbJWSHfFcC8JhoPRuRsb9
  S+HkAi61prJcU7lMRTwuCldbWcLe29YTdWVTJGGJtnYr1gxGkB25NSAop8e8LFHS
  o74RoOdBj5viL1MvMsLuBN3vAAAAwQDk+hvndwyBXUpfBR7EtECabpLJ7NZpFK0H
  FPP6KMLqhKw8Hp66d5w3EAbGnvWITLC74NXwJu1ncIwGPuabPVqP740AMjEe6IDx
  K283ia8i5IrmOquZVhfJeYwEdxfyrttVoiQKaVZJdF43oV2rj7LLdqvoGpqmOG6t
  Xgkh9i3Zz7uOuOSCk25mygEgZ7l7SFGAo+CfS2SNNXxpbBH6/1L8zakxPWTF+lnZ
  e3n5yoBB/CbNrmj5mwfPvW3190N0dDMAAAAVdXBjczJATEFQVE9QLUFJT1BNTUsw
  AQIDBAUG
  -----END OPENSSH PRIVATE KEY-----